name: Publish Python Package to PyPI

on:
  workflow_dispatch:  # ✅ Manual run
  push:
    tags:
      - 'v*'  # Only run when you push version tags like v0.1.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for Trusted Publishing

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build package
        run: |
          python -m pip install build
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
